import { PackagesType } from '@/types';

export const packages: PackagesType[] = [
  {
    id: '1',
    name: 'Basic Logo Package',
    price: '100.00',
    discountedPrice: ' $38.99',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Logo Design',
    points: [
      { heading: false, message: '3 Custom Logo Design Concepts' },
      { heading: false, message: '1 Dedicated Designer' },
      { heading: false, message: '4 Revisions' },
      { heading: false, message: '48 to 72 hours TAT' },
      { heading: false, message: '100% Unique Design Guarantee' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee *' },
    ],
  },
  {
    id: '2',
    name: 'Start Up Logo Package',
    price: '200.00',
    discountedPrice: ' $79.99',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Logo Design',
    points: [
      { heading: false, message: '5 Custom Logo Design Concepts' },
      { heading: false, message: 'By 2 Designers' },
      { heading: false, message: 'UNLIMITED Revisions' },
      { heading: false, message: '48 to 72 hours TAT' },
      { heading: false, message: 'Final File Format ( JPG format only)' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Unique Design Guarantee' },
      { heading: false, message: '100% Money Back Guarantee *' },
    ],
  },
  {
    id: '3',
    name: 'Professional Logo Package',
    price: '300.00',
    discountedPrice: ' $150.99',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Logo Design',
    points: [
      { heading: false, message: 'UNLIMITED Logo Design Concepts' },
      { heading: false, message: 'By 4 Designers' },
      { heading: false, message: 'UNLIMITED Revisions' },
      {
        heading: false,
        message: 'Stationary Design (Business Card, Letterhead, Envelope)',
      },
      { heading: false, message: 'FREE MS Word Letterhead' },
      { heading: false, message: '48 to 72 hours TAT' },
      { heading: false, message: 'All Final Files Format ( PSD, PNG, JPG)' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Unique Design Guarantee' },
      { heading: false, message: '100% Money Back Guarantee *' },
    ],
  },
  {
    id: '4',
    name: 'Elite Logo Package',
    price: '500.00',
    discountedPrice: ' $250.99',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Logo Design',
    points: [
      { heading: false, message: 'UNLIMITED Logo Design Concepts' },
      { heading: false, message: 'By 5 Award Winning Designers' },
      {
        heading: false,
        message: 'Stationary Design (Business Card, Letterhead, Envelope)',
      },
      { heading: false, message: 'Icon Design' },
      { heading: false, message: 'UNLIMITED Revisions' },
      { heading: false, message: 'FREE MS Word Letterhead' },
      { heading: false, message: 'Free Email Signature' },
      {
        heading: false,
        message: 'All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)',
      },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Unique Design Guarantee' },
      { heading: false, message: '100% Money Back Guarantee *' },
      { heading: false, message: '48 to 72 hours TAT' },
    ],
  },
  {
    id: '5',
    name: 'Business Logo Package',
    price: '600.00',
    discountedPrice: ' $344.99',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Logo Design',
    points: [
      { heading: false, message: 'UNLIMITED Logo Design Concepts' },
      { heading: false, message: 'By 8 Award Winning Designers' },
      { heading: false, message: 'UNLIMITED Revisions' },
      {
        heading: false,
        message:
          '2 Stationary Design Sets (Business Card, Letterhead, Envelope)',
      },
      { heading: false, message: 'Icon Design' },
      {
        heading: false,
        message: 'Double Sided Flyer Design / Bi-Fold Brochure',
      },
      { heading: false, message: 'FREE MS Word Letterhead' },
      { heading: false, message: 'Free Email Signature' },
      {
        heading: false,
        message: 'All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)',
      },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Unique Design Guarantee' },
      { heading: false, message: '100% Money Back Guarantee *' },
    ],
  },
  {
    id: '6',
    name: 'Gold Logo Package',
    price: '848.00',
    discountedPrice: ' $425.99',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Logo Design',
    points: [
      { heading: false, message: 'UNLIMITED Logo Design Concepts' },
      { heading: false, message: 'By 8 Award Winning Designers' },
      { heading: false, message: 'Icon Design' },
      { heading: false, message: 'UNLIMITED Revisions' },
      {
        heading: false,
        message:
          '2 Stationary Design Sets (Business Card, Letterhead, Envelope)',
      },
      { heading: false, message: 'FREE MS Word Letterhead' },
      { heading: false, message: 'Free Email Signature' },
      { heading: false, message: '3 Page Custom Website' },
      { heading: false, message: '2 Stock Photos' },
      { heading: false, message: '2 Banner Designs' },
      { heading: false, message: 'jQuery Slider' },
      {
        heading: false,
        message: 'All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)',
      },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Unique Design Guarantee' },
      { heading: false, message: '100% Money Back Guarantee *' },
    ],
  },
  {
    id: '7',
    name: 'Basic Website Package',
    price: '500.00',
    discountedPrice: ' $249.99',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Website Development',
    points: [
      { heading: false, message: '1 Page Website Design' },
      { heading: false, message: 'HTML Based' },
      { heading: false, message: '1 Banner Design' },
      { heading: false, message: 'Contact/Query Form' },
      { heading: false, message: '3 Revisions' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '8',
    name: 'Start Up Website Package',
    price: '788.00',
    discountedPrice: ' $394.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Website Development',
    points: [
      { heading: false, message: '3 Page Website Design' },
      { heading: false, message: 'HTML Based' },
      { heading: false, message: 'Hover Effects' },
      { heading: false, message: '2 Banner Designs' },
      { heading: false, message: 'Sliding Banner' },
      { heading: false, message: '2 Stock Photos (You can provide us more)' },
      { heading: false, message: 'Contact/Query Form' },
      { heading: false, message: '3 Professional Email ID’s' },
      { heading: false, message: '6 Revisions' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '9',
    name: 'Professional Website Package',
    price: '1639.00',
    discountedPrice: ' $819.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Website Development',
    points: [
      { heading: false, message: 'Up to 5 Pages Website Design' },
      { heading: false, message: '3 Stock Photos (You can provide us more)' },
      { heading: false, message: '3 Banner Designs' },
      { heading: false, message: 'Sliding Banner' },
      { heading: false, message: 'Hover Effects' },
      { heading: false, message: 'Content Management System (WordPress)' },
      { heading: false, message: '5 Professional Email ID’s' },
      { heading: false, message: 'Search Engine Submission' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: false, message: 'Industry specified Team of Expert Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '10',
    name: 'Elite Website Package',
    price: '2799.00',
    discountedPrice: ' $1399.99',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Website Development',
    points: [
      { heading: false, message: 'Unique 5 Pages Website Design' },
      { heading: false, message: 'Custom, Interactive, Dynamic & High End Web Design' },
      { heading: false, message: 'Custom WordPress Development' },
      { heading: false, message: '5 Stock Images' },
      { heading: false, message: '5 Banner Designs' },
      { heading: false, message: 'Sliding Banners' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Special Hoover Effects' },
      { heading: false, message: 'Content Management System (WordPress)' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: 'Online Appointment/Booking/Scheduling/Online Ordering Integration (If Required)' },
      { heading: false, message: '5 Professional Email ID’s' },
      { heading: false, message: 'Google Friendly Sitemap' },
      { heading: false, message: 'Search Engine Submission' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: false, message: 'Industry specified Team of Expert Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '11',
    name: 'Identity Website Package',
    price: '3599.99',
    discountedPrice: ' $1799.99',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Website Development',
    points: [
      { heading: false, message: '10 Unique Pages Website Design' },
      { heading: false, message: 'Custom, Interactive, Dynamic & High End Design' },
      { heading: false, message: 'Customize WordPress (or) PHP Development' },
      { heading: false, message: 'Interactive Sliding Banners' },
      { heading: false, message: '10 Stock Images' },
      { heading: false, message: '10 Banner Designs' },
      { heading: false, message: 'Special Hoover Effects' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Content Management System (WordPress or Custom)' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: 'Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)' },
      { heading: false, message: 'Online Payment Integration (Optional)' },
      { heading: false, message: '10 Professional Email ID’s' },
      { heading: false, message: 'Google Friendly Sitemap' },
      { heading: false, message: 'Search Engine Submission' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: false, message: 'Industry specified Team of Award Winning Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: ' *NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '12',
    name: 'Corporate Website Package',
    price: '6799.99',
    discountedPrice: ' $3399.99',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Website Development',
    points: [
      { heading: false, message: '15 to 20 Unique Pages Website Design' },
      { heading: false, message: 'Custom Made, Interactive, Dynamic & High End Design' },
      { heading: false, message: 'Customized WordPress & PHP Development' },
      { heading: false, message: 'Interactive Sliding Banners' },
      { heading: false, message: 'Up to 15 Custom Made Banner Designs' },
      { heading: false, message: '15 Stock Images' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Special Hoover Effects' },
      { heading: false, message: 'Content Management System' },
      { heading: false, message: 'Online Appointment/Booking/Scheduling/Online Ordering Integration (Optional)' },
      { heading: false, message: 'Online Payment Integration (Optional)' },
      { heading: false, message: 'Multi Lingual (Optional)' },
      { heading: false, message: 'Custom Dynamic Forms (Optional)' },
      { heading: false, message: 'Signup Area (For Newsletters, Offers etc.)' },
      { heading: false, message: 'Search Bar' },
      { heading: false, message: 'Live Feeds of Social Networks integration (Optional)' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: 'Up to 15 Professional Email ID’s' },
      { heading: false, message: 'Google Friendly Sitemap' },
      { heading: false, message: 'Search Engine Submission' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: false, message: 'Industry specified Team of Award Winning Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '13',
    name: 'Business Website Package',
    price: '5998.00',
    discountedPrice: ' $2999.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Website Development',
    points: [
      { heading: false, message: '15 Seconds 2D Explainer Video' },
      { heading: false, message: 'Voice - Over & Sound Effects' },
      { heading: false, message: 'Professional Script Writing' },
      { heading: false, message: 'Storyboard' },
      { heading: false, message: 'SEO Meta Tags' },
      { heading: false, message: '15 to 20 Pages Website' },
      { heading: false, message: 'Custom Made, Interactive, Dynamic & High End Design' },
      { heading: false, message: 'Custom WP (or) Custom PHP Development' },
      { heading: false, message: '1 jQuery Slider Banner' },
      { heading: false, message: 'Up to 10 Custom Made Banner Designs' },
      { heading: false, message: '10 Stock Images' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Special Hoover Effects' },
      { heading: false, message: 'Content Management System (CMS)' },
      { heading: false, message: 'Online Appointment/Scheduling/Online Ordering Integration (Optional)' },
      { heading: false, message: 'Online Payment Integration (Optional)' },
      { heading: false, message: 'Multi Lingual (Optional)' },
      { heading: false, message: 'Custom Dynamic Forms (Optional)' },
      { heading: false, message: 'Signup Area (For Newsletters, Offers etc.)' },
      { heading: false, message: 'Search Bar' },
      { heading: false, message: 'Live Feeds of Social Networks integration (Optional)' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: 'FREE 5 Years Domain Name' },
      { heading: false, message: 'Free Google Friendly Sitemap' },
      { heading: false, message: 'Search Engine Submission' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: false, message: 'Industry Specified Team of Expert Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: false, message: 'Dedicated Accounts Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Unique Design Guarantee' },
      { heading: false, message: '100% Money Back Guarantee *' },
    ],
  },
  {
    id: '14',
    name: 'E-Commerce Basic Package',
    price: '999.00',
    discountedPrice: ' $449.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Ecommerce Solutions',
    points: [
      { heading: false, message: 'E-Commerce Website Design and Development' },
      { heading: false, message: 'Theme Based Design' },
      { heading: false, message: '2 Banner Designs' },
      { heading: false, message: 'Sliding Banner' },
      { heading: false, message: '3 Stock Photos' },
      { heading: false, message: '06 Revisions' },
      { heading: false, message: 'Hover Effects' },
      { heading: false, message: 'Up to 10 Products' },
      { heading: false, message: 'Up to 3 Categories' },
      { heading: false, message: 'Content/Inventory Management System' },
      { heading: false, message: 'Easy Product Search Bar' },
      { heading: false, message: 'Shopping Cart Integration' },
      { heading: false, message: 'Payment Module Integration' },
      { heading: false, message: 'Direct Checkout' },
      { heading: false, message: 'Sign up Checkout' },
      { heading: false, message: 'Wishlist' },
      { heading: false, message: 'Complete W3C Validation' },
      { heading: false, message: 'Dedicated Team of Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '15',
    name: 'E-Commerce Start Up Package',
    price: '1699.00',
    discountedPrice: ' $699.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Ecommerce Solutions',
    points: [
      { heading: false, message: 'E-Commerce Website Design and Development' },
      { heading: false, message: 'High-end Theme Based Design' },
      { heading: false, message: '5 Banner Designs' },
      { heading: false, message: 'Sliding Banner' },
      { heading: false, message: '5 Stock Photos' },
      { heading: false, message: '12 Revisions' },
      { heading: false, message: 'Hover Effects' },
      { heading: false, message: 'Up to 25 Products' },
      { heading: false, message: 'Up to 5 Categories' },
      { heading: false, message: 'Content/Inventory Management System' },
      { heading: false, message: 'Easy Product Search Bar' },
      { heading: false, message: 'Shopping Cart Integration' },
      { heading: false, message: 'Payment Module Integration' },
      { heading: false, message: 'Direct Checkout' },
      { heading: false, message: 'Sign up Checkout' },
      { heading: false, message: 'Wishlist' },
      { heading: false, message: 'Social Media Pages Integration' },
      { heading: false, message: 'Sitemap' },
      { heading: false, message: 'Complete W3C Validation' },
      { heading: false, message: 'Dedicated Team of Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: ' 100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
    ],
  },
  {
    id: '16',
    name: 'E-Commerce Elite Package',
    price: '3399.00',
    discountedPrice: ' $1699.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Ecommerce Solutions',
    points: [
      { heading: false, message: 'E-Commerce Website Design and Development' },
      { heading: false, message: 'Customized Tailor-Made Design' },
      { heading: false, message: 'Professional, Modern, Unique Design' },
      { heading: false, message: '10 Banner Designs' },
      { heading: false, message: 'Sliding Banner' },
      { heading: false, message: '10 Stock Photos' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Special Hover Effects' },
      { heading: false, message: 'Up to 500 Products' },
      { heading: false, message: 'Up to 25 Categories' },
      { heading: false, message: 'Product Reviews & Ratings' },
      { heading: false, message: 'Content/Inventory Management System' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: 'Easy Product Search Bar' },
      { heading: false, message: 'Shopping Cart Integration' },
      { heading: false, message: 'Payment Module Integration' },
      { heading: false, message: 'Direct Checkout' },
      { heading: false, message: 'Sign up Checkout' },
      { heading: false, message: 'Wishlist' },
      { heading: false, message: 'Social Media Pages Integration' },
      { heading: false, message: 'Blog page (If Required)' },
      { heading: false, message: 'Sitemap' },
      { heading: false, message: 'Complete W3C Validation' },
      { heading: false, message: 'Dedicated Team of Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: ' *NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '17',
    name: 'E-Commerce Professional Package',
    price: '2399.00',
    discountedPrice: ' $1199.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Ecommerce Solutions',
    points: [
      { heading: false, message: 'E-Commerce Website Design and Development' },
      { heading: false, message: 'Customized Theme Based Design' },
      { heading: false, message: '7 Banner Designs' },
      { heading: false, message: 'Sliding Banner' },
      { heading: false, message: '7 Stock Photos' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Hover Effects' },
      { heading: false, message: 'Up to 100 Products' },
      { heading: false, message: 'Up to 10 Categories' },
      { heading: false, message: 'Content/Inventory Management System' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: 'Easy Product Search Bar' },
      { heading: false, message: 'Shopping Cart Integration' },
      { heading: false, message: 'Payment Module Integration' },
      { heading: false, message: 'Direct Checkout' },
      { heading: false, message: 'Sign up Checkout' },
      { heading: false, message: 'Wishlist' },
      { heading: false, message: 'Social Media Pages Integration' },
      { heading: false, message: 'Sitemap' },
      { heading: false, message: 'Complete W3C Validation' },
      { heading: false, message: 'Dedicated Team of Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: false, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '18',
    name: 'E-Commerce Identity Package',
    price: '4999.00',
    discountedPrice: ' $2499.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Ecommerce Solutions',
    points: [
      { heading: false, message: 'E-Commerce Website Design and Development' },
      { heading: false, message: 'Customized Tailor-Made Design' },
      { heading: false, message: 'Professional, Modern, Interactive, Dynamic, Unique Design' },
      { heading: false, message: 'User-friendly Navigation' },
      { heading: false, message: '20 Banner Designs' },
      { heading: false, message: 'Sliding Banner' },
      { heading: false, message: '20 Stock Photos' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Special Hover Effects' },
      { heading: false, message: 'Content/Inventory Management System' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: 'Unlimited Products' },
      { heading: false, message: 'Unlimited Categories' },
      { heading: false, message: 'Product Reviews & Ratings' },
      { heading: false, message: 'Product Summary Reports (Out of stock / Most Sold / Lowest sale etc) By Date' },
      { heading: false, message: 'Product Rating' },
      { heading: false, message: 'Product Detail with Similar Product Range' },
      { heading: false, message: 'Product Comparison' },
      { heading: false, message: 'Discounted Products Showcase' },
      { heading: false, message: 'New Arrival Products Showcase' },
      { heading: false, message: 'Discount Coupons' },
      { heading: false, message: 'Easy Product Search Bar' },
      { heading: false, message: 'Shopping Cart Integration' },
      { heading: false, message: 'Payment Module Integration' },
      { heading: false, message: 'Direct Checkout' },
      { heading: false, message: 'Sign up Checkout' },
      { heading: false, message: 'Wishlist' },
      { heading: false, message: 'Bulk Product Upload From Excel Sheet' },
      { heading: false, message: 'Export order into excel sheet' },
      { heading: false, message: 'Social Media Pages Integration' },
      { heading: false, message: 'Facebook Shop Setup' },
      { heading: false, message: 'Blog page (If Required)' },
      { heading: false, message: 'Sitemap' },
      { heading: false, message: 'Complete W3C Validation' },
      { heading: false, message: 'Dedicated Team of Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '19',
    name: 'E-Commerce Corporate Package',
    price: '5399.00',
    discountedPrice: ' $3699.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Ecommerce Solutions',
    points: [
      { heading: false, message: 'E-Commerce Website Design and Development' },
      { heading: false, message: 'Customized Tailor-Made Design' },
      { heading: false, message: 'Professional, Modern, Interactive, Dynamic, Unique Design' },
      { heading: false, message: 'User-friendly Navigation' },
      { heading: false, message: '20 Banner Designs' },
      { heading: false, message: 'Sliding Banner' },
      { heading: false, message: '20 Stock Photos' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Special Hover Effects' },
      { heading: false, message: 'Content/Inventory Management System' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: 'Unlimited Products' },
      { heading: false, message: 'Unlimited Categories' },
      { heading: false, message: 'Product Reviews & Ratings' },
      { heading: false, message: 'Product Summary Reports (Out of stock / Most Sold / Lowest sale etc) By Date' },
      { heading: false, message: 'Product Rating' },
      { heading: false, message: 'Product Detail with Similar Product Range' },
      { heading: false, message: 'Product Comparison' },
      { heading: false, message: 'Discounted Products Showcase' },
      { heading: false, message: 'New Arrival Products Showcase' },
      { heading: false, message: 'Discount Coupons' },
      { heading: false, message: 'Easy Product Search Bar' },
      { heading: false, message: 'Shopping Cart Integration' },
      { heading: false, message: 'Payment Module Integration' },
      { heading: false, message: 'Direct Checkout' },
      { heading: false, message: 'Sign up Checkout' },
      { heading: false, message: 'Wishlist' },
      { heading: false, message: 'Bulk Product Upload From Excel Sheet' },
      { heading: false, message: 'Export order into excel sheet' },
      { heading: false, message: 'Social Media Pages Integration' },
      { heading: false, message: 'Facebook Shop Setup' },
      { heading: false, message: 'Blog page (If Required)' },
      { heading: false, message: 'Sitemap' },
      { heading: false, message: 'Complete W3C Validation' },
      { heading: false, message: 'Dedicated Team of Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '20',
    name: 'Basic Video Package',
    price: '1598.00',
    discountedPrice: ' $499.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Animation',
    points: [
      { heading: false, message: '30 Second Video' },
      { heading: false, message: 'Professional Script' },
      { heading: false, message: 'Storyboard' },
      { heading: false, message: 'Animation' },
      { heading: false, message: 'Voice - Over & Sound Effects' },
      { heading: false, message: '4 weeks Delivery' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '21',
    name: 'Classic  Video Package',
    price: '2198.00',
    discountedPrice: ' $99.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Animation',
    points: [
      { heading: false, message: '60 Second Video' },
      { heading: false, message: 'Professional Script' },
      { heading: false, message: 'Sample Theme' },
      { heading: false, message: 'Storyboard' },
      { heading: false, message: 'Animation' },
      { heading: false, message: 'Voice - Over & Sound Effects' },
      { heading: false, message: '5 weeks Delivery' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '22',
    name: 'Premium  Video Package',
    price: '2998.00',
    discountedPrice: ' $1499.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Animation',
    points: [
      { heading: false, message: '90 Second Video' },
      { heading: false, message: 'Professional Script' },
      { heading: false, message: 'Sample Theme' },
      { heading: false, message: 'Storyboard' },
      { heading: false, message: 'Animation' },
      { heading: false, message: 'Voice - Over & Sound Effects' },
      { heading: false, message: '6 Weeks Delivery' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '23',
    name: 'Unlimited  Video Package',
    price: '4590.00',
    discountedPrice: ' $2299.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Animation',
    points: [
      { heading: false, message: '120 Second Video' },
      { heading: false, message: 'Professional Script' },
      { heading: false, message: 'Sample Theme' },
      { heading: false, message: 'Storyboard' },
      { heading: false, message: 'Animation' },
      { heading: false, message: 'Voice - Over & Sound Effects' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '24',
    name: 'Basic Illustrative Package',
    price: '588.00',
    discountedPrice: ' $294.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Illustration',
    points: [
      { heading: false, message: '3 Custom Logo Design Concepts' },
      { heading: false, message: 'By 2 Designers' },
      { heading: false, message: 'UNLIMITED Revisions' },
      { heading: false, message: '48 to 72 hours TAT' },
      { heading: false, message: 'All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '25',
    name: 'Startup Illustrative Package',
    price: '788.00',
    discountedPrice: ' $394.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Illustration',
    points: [
      { heading: false, message: '4 Custom Logo Design Concepts' },
      { heading: false, message: 'By 3 Designers' },
      { heading: false, message: '48 to 72 hours TAT' },
      { heading: false, message: 'UNLIMITED Revisions' },
      { heading: false, message: 'All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)' },
      { heading: false, message: '100% Money Back Guarantee *' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
    ],
  },
  {
    id: '26',
    name: 'Professional Illustrative Package',
    price: '1188.00',
    discountedPrice: ' $594.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Illustration',
    points: [
      { heading: false, message: 'UNLIMITED Logo Design Concepts' },
      { heading: false, message: 'By 4 Designers' },
      { heading: false, message: 'UNLIMITED Revisions' },
      { heading: false, message: '24 to 48 hours TAT' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '27',
    name: '3D Logo Illustrative Package',
    price: '1080.00',
    discountedPrice: ' $544.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Illustration',
    points: [
      { heading: false, message: '3 Unique 3D Logo Concepts' },
      { heading: false, message: 'Light Effects and VFX' },
      { heading: false, message: 'Fully Rendered' },
      { heading: false, message: 'Multiple 3D Angles' },
      { heading: false, message: 'By 3 Award Winning Designers' },
      { heading: false, message: '72 hours Turnaround Time' },
      { heading: false, message: ' UNLIMITED Revisions' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '28',
    name: 'Startup Collateral Package',
    price: '198.00',
    discountedPrice: ' $99.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Marketing Collateral',
    points: [
      { heading: false, message: '2 Stationery Design Set' },
      { heading: false, message: 'FREE Fax Template' },
      { heading: false, message: 'Print Ready Formats' },
      { heading: false, message: 'UNLIMITED Revisions' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee *' },
    ],
  },
  {
    id: '29',
    name: 'Collateral Classic Package',
    price: '398.00',
    discountedPrice: ' $199.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Marketing Collateral',
    points: [
      { heading: false, message: '2 Stationery Design Set' },
      { heading: false, message: 'UNLIMITED Revisions' },
      { heading: false, message: 'Flyer Design' },
      { heading: false, message: 'Brochure Design (Bi-fold/Tri-fold)' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee *' },
    ],
  },
  {
    id: '30',
    name: 'Collateral Classic Package',
    price: '789.00',
    discountedPrice: ' $399.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Marketing Collateral',
    points: [
      { heading: false, message: '2 Stationery Design Set' },
      { heading: false, message: 'Packaging Design' },
      { heading: false, message: 'UNLIMITED Revisions' },
      { heading: false, message: 'T-Shirt Design' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee *' },
    ],
  },
  {
    id: '31',
    name: 'Unlimited  Classic Package',
    price: '1998.00',
    discountedPrice: ' $499.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Marketing Collateral',
    points: [
      { heading: false, message: '2 Stationery Design Set' },
      { heading: false, message: 'Menu Card Design' },
      { heading: false, message: 'T-Shirt Design' },
      { heading: false, message: '1 Banner Design' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee *' },
    ],
  },
  {
    id: '32',
    name: 'Basic Plan Package',
    price: '7000.00',
    discountedPrice: ' $3500.00',
    desc: '(3 MONTHS PLAN)',
    category: 'Seo',
    points: [
      { heading: false, message: 'Prior Analysis' },
      { heading: false, message: 'Business Analysis' },
      { heading: false, message: 'Consumer Analysis' },
      { heading: false, message: 'Competitor Analysis' },
      { heading: false, message: '15 Selected Keywords Targeting' },
      { heading: false, message: '15 Pages Keyword Targeted' },
      { heading: false, message: 'Webpage Optimization' },
      { heading: false, message: 'Meta Tags Creation' },
      { heading: false, message: 'Keyword Optimization' },
      { heading: false, message: 'Image Optimization' },
      { heading: false, message: 'Inclusion of anchors' },
      { heading: false, message: 'Tracking & Analysis' },
      { heading: false, message: 'Google Analytics Installation' },
      { heading: false, message: 'Google Webmaster Installation' },
      { heading: false, message: 'Call To Action Plan' },
      { heading: false, message: 'Creation of Sitemaps' },
      { heading: false, message: 'Reporting' },
      { heading: false, message: 'Monthly Reporting' },
      { heading: false, message: 'Recommendation' },
      { heading: false, message: 'Email Support' },
      { heading: false, message: 'Phone Support' },
      { heading: false, message: 'Off Page Optimization' },
      { heading: false, message: 'Social Bookmarking' },
      { heading: false, message: 'Slide Share Marketing' },
      { heading: false, message: 'Forums/FAQ’s' },
      { heading: false, message: 'Link Building' },
      { heading: false, message: 'Directory Submission' },
      { heading: false, message: 'Local Business Listings' },
    ],
  },
  {
    id: '33',
    name: 'Premium Plan Package',
    price: '12000.00',
    discountedPrice: ' $6000.00',
    desc: '(6 MONTHS PLAN)',
    category: 'Seo',
    points: [
      { heading: false, message: 'Prior Analysis' },
      { heading: false, message: 'Business Analysis' },
      { heading: false, message: 'Consumer Analysis' },
      { heading: false, message: 'Competitor Analysis' },
      { heading: false, message: '30 Selected Keywords Targeting' },
      { heading: false, message: '30 Pages Keyword Targeted' },
      { heading: false, message: 'Webpage Optimization' },
      { heading: false, message: 'Meta Tags Creation' },
      { heading: false, message: 'Keyword Optimization' },
      { heading: false, message: 'Image Optimization' },
      { heading: false, message: 'Inclusion of anchors Tags' },
      { heading: false, message: 'Inclusion of anchors Indexing Modifications' },
      { heading: false, message: 'Tracking & Analysis' },
      { heading: false, message: 'Google Places Inclusions' },
      { heading: false, message: 'Google Analytics Installation' },
      { heading: false, message: 'Google Webmaster Installation' },
      { heading: false, message: 'Call To Action Plan' },
      { heading: false, message: 'Creation of Sitemaps' },
      { heading: false, message: 'Reporting' },
      { heading: false, message: 'Monthly Reporting' },
      { heading: false, message: 'Recommendation' },
      { heading: false, message: 'Email Support' },
      { heading: false, message: 'Phone Support' },
      { heading: false, message: 'Off Page Optimization' },
      { heading: false, message: 'Social Bookmarking' },
      { heading: false, message: 'Slide Share Marketing' },
      { heading: false, message: 'Forums/FAQ’s' },
      { heading: false, message: 'Link Building' },
      { heading: false, message: 'Directory Submission' },
      { heading: false, message: 'Local Business Listings' },
    ],
  },
  {
    id: '34',
    name: 'Platinum Plan Package',
    price: '16000.00',
    discountedPrice: ' $8000.00',
    desc: '(12 MONTHS PLAN)',
    category: 'Seo',
    points: [
      { heading: false, message: 'Prior Analysis' },
      { heading: false, message: 'Business Analysis' },
      { heading: false, message: 'Consumer Analysis' },
      { heading: false, message: 'Competitor Analysis' },
      { heading: false, message: '70 Selected Keywords Targeting' },
      { heading: false, message: '50 Pages Keyword Targeted' },
      { heading: false, message: 'Webpage Optimization' },
      { heading: false, message: 'Meta Tags Creation' },
      { heading: false, message: 'Keyword Optimization' },
      { heading: false, message: 'Image Optimization' },
      { heading: false, message: 'Inclusion of anchors Tags' },
      { heading: false, message: 'Inclusion of anchors Indexing Modifications' },
      { heading: false, message: 'Tracking & Analysis' },
      { heading: false, message: 'Google Places Inclusions' },
      { heading: false, message: 'Google Analytics Installation' },
      { heading: false, message: 'Google Webmaster Installation' },
      { heading: false, message: 'Call To Action Plan' },
      { heading: false, message: 'Creation of Sitemaps' },
      { heading: false, message: 'Reporting' },
      { heading: false, message: 'Monthly Reporting' },
      { heading: false, message: 'Recommendation' },
      { heading: false, message: 'Email Support' },
      { heading: false, message: 'Phone Support' },
      { heading: false, message: 'Off Page Optimization' },
      { heading: false, message: 'Social Bookmarking' },
      { heading: false, message: 'Slide Share Marketing' },
      { heading: false, message: 'Forums/FAQ’s' },
      { heading: false, message: 'Link Building' },
      { heading: false, message: 'Directory Submission' },
      { heading: false, message: 'Local Business Listings' },
      { heading: false, message: 'Blog Content Creation' },
      { heading: false, message: 'Local SEO' },
    ],
  },
  {
    id: '35',
    name: 'Startup Social Package',
    price: '198.00',
    discountedPrice: ' $99.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Digital Marketing',
    points: [
      { heading: false, message: 'Cover Photo Design' },
      { heading: false, message: 'Profile Picture Design' },
      { heading: false, message: 'Welcome Page Design' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '36',
    name: 'Classic Social Package',
    price: '298.00',
    discountedPrice: ' $149.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Digital Marketing',
    points: [
      { heading: false, message: 'Cover Photo Design' },
      { heading: false, message: 'Profile Picture Design' },
      { heading: false, message: 'Welcome Page Design' },
      { heading: false, message: 'Twitter Page Design' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: ' 100% Money Back Guarantee *' },
    ],
  },
  {
    id: '37',
    name: 'Premium Social Package',
    price: '398.00',
    discountedPrice: ' $199.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Digital Marketing',
    points: [
      { heading: false, message: 'Cover Photo Design' },
      { heading: false, message: 'Profile Picture Design' },
      { heading: false, message: 'Welcome Page Design' },
      { heading: false, message: 'Twitter Page Design' },
      { heading: false, message: 'YouTube Page Design' },
      { heading: false, message: 'Unlimited Revisions' },
    ],
  },
  {
    id: '38',
    name: 'Unlimited Social Package',
    price: '1998.00',
    discountedPrice: ' $999.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Digital Marketing',
    points: [
      { heading: false, message: '2 Cover Photo Designs' },
      { heading: false, message: 'Profile Picture Design' },
      { heading: false, message: 'Welcome Page Design' },
      { heading: false, message: 'Twitter Page Design' },
      { heading: false, message: 'YouTube Page Design' },
      { heading: false, message: 'Google+ Page Design' },
    ],
  },
  {
    id: '39',
    name: 'Web Content Basic Package',
    price: '319.00',
    discountedPrice: ' $129.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Creative Copywriting',
    points: [
      { heading: false, message: '1 Page Professional Copywriting Service' },
      { heading: false, message: 'Creative & Well-Written by 1 Professional Copywriter' },
      { heading: false, message: 'Industry Specified Expert Copywriter' },
      { heading: false, message: '300 Words Per Page' },
      { heading: false, message: '5 Revisions' },
      { heading: false, message: '3 to 4 Business Days Rotation' },
      { heading: false, message: 'According To Your Exact Requirements' },
      { heading: false, message: 'Proofing by our in-house experts' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Original Content' },
      { heading: false, message: '100% Approval Assurance' },
      { heading: false, message: '30 Days Refund Warranty' },
    ],
  },
  {
    id: '40',
    name: 'Web Content Start Up Package',
    price: '1849.00',
    discountedPrice: ' $499.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Creative Copywriting',
    points: [
      { heading: false, message: '5 Pages Professional Copywriting Service' },
      { heading: false, message: 'Creative & Well-Written by 2 Professional Copywriters' },
      { heading: false, message: 'Industry Specified Expert Copywriters' },
      { heading: false, message: '300 Words Per Page' },
      { heading: false, message: '10 Revisions' },
      { heading: false, message: '5 to 7 Business Days Rotation' },
      { heading: false, message: 'According To Your Exact Requirements' },
      { heading: false, message: 'Proofing by our in-house experts' },
      { heading: false, message: 'FREE Meta details – With each custom page, we will provide a catchy title, keywords and page description.' },
      { heading: false, message: 'SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Original Content' },
      { heading: false, message: '100% Approval Assurance' },
      { heading: false, message: '30 Days Refund Warranty' },
    ],
  },
  {
    id: '41',
    name: 'Web Content Professional Package',
    price: '2119.00',
    discountedPrice: ' $849.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Creative Copywriting',
    points: [
      { heading: false, message: '10 Pages Professional Copywriting Service' },
      { heading: false, message: 'Creative & Well-Written by 2 Professional Copywriters' },
      { heading: false, message: 'Industry Specified Expert Copywriters' },
      { heading: false, message: '300 Words Per Page' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: '7 to 10 Business Days Rotation' },
      { heading: false, message: 'According To Your Exact Requirements' },
      { heading: false, message: 'Proofing by our in-house experts' },
      { heading: false, message: 'FREE Meta details – With each custom page, we will provide a catchy title, keywords and page description.' },
      { heading: false, message: 'SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Original Content' },
      { heading: false, message: '100% Approval Assurance' },
      { heading: false, message: '30 Days Refund Warranty' },
    ],
  },
  {
    id: '42',
    name: 'Web Content Elite Package',
    price: '4519.00',
    discountedPrice: ' $1849.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Creative Copywriting',
    points: [
      { heading: false, message: 'Up to 20 Pages Professional Copywriting Service' },
      { heading: false, message: 'Creative & Well-Written by 3 Professional Copywriters' },
      { heading: false, message: 'Industry Specified Expert Copywriters' },
      { heading: false, message: '300 Words Per Page' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: '7 to 10 Business Days Rotation' },
      { heading: false, message: 'According To Your Exact Requirements' },
      { heading: false, message: 'Proofing by our in-house experts' },
      { heading: false, message: 'FREE Meta details – With each custom page, we will provide a catchy title, keywords and page description.' },
      { heading: false, message: 'SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Original Content' },
      { heading: false, message: '100% Approval Assurance' },
      { heading: false, message: '30 Days Refund Warranty' },
    ],
  },
  {
    id: '43',
    name: 'Web Content Identity Package',
    price: '369.00',
    discountedPrice: ' $149.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Creative Copywriting',
    points: [
      { heading: false, message: '1 Creative, Fresh & Well-Written Article' },
      { heading: false, message: 'By 1 Professional Copywriter' },
      { heading: false, message: 'Industry Specified Expert Copywriter' },
      { heading: false, message: '400 Words Per Page' },
      { heading: false, message: '3 to 5 Business Days Rotation' },
      { heading: false, message: '5 Revisions' },
      { heading: false, message: 'According To Your Exact Requirements' },
      { heading: false, message: 'Written on Your Specified Topic/Keyword' },
      { heading: false, message: 'Proofing by our in-house experts' },
      { heading: false, message: 'Free Submission on any article marketing directories /blog (If required)' },
      { heading: false, message: 'SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Original Content' },
      { heading: false, message: '100% Approval Assurance' },
      { heading: false, message: '30 Days Refund Warranty' },
    ],
  },
  {
    id: '44',
    name: 'Web Content Corporate Package',
    price: '319.00',
    discountedPrice: ' $129.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Creative Copywriting',
    points: [
      { heading: false, message: '1 Creative, Fresh & Well-Written Article' },
      { heading: false, message: 'By 1 Professional Copywriter' },
      { heading: false, message: 'Industry Specified Expert Copywriter' },
      { heading: false, message: '400 Words Per Page' },
      { heading: false, message: '3 to 5 Business Days Rotation' },
      { heading: false, message: '5 Revisions' },
      { heading: false, message: 'According To Your Exact Requirements' },
      { heading: false, message: 'Written on Your Specified Topic/Keyword' },
      { heading: false, message: 'Proofing by our in-house experts' },
      { heading: false, message: 'Free Submission on any article marketing directories /blog (If required)' },
      { heading: false, message: 'SEO friendly – Your keyword(s) will be placed in the title, the first & last paragraphs and throughout the web copy in a natural and fluent manner' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Original Content' },
      { heading: false, message: '100% Approval Assurance' },
      { heading: false, message: '30 Days Refund Warranty' },
    ],
  },
  {
    id: '45',
    name: 'Basic Combo Package',
    price: '1239.00',
    discountedPrice: ' $619.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Combo',
    points: [
      { heading: true, message: 'Logo Design' },
      { heading: false, message: '5 Custom Logo Design Concepts' },
      { heading: false, message: 'By 2 Designers' },
      { heading: false, message: 'Icon Design' },
      { heading: false, message: 'All Final File Formats' },
      { heading: true, message: 'Business Stationary' },
      { heading: false, message: 'Business Card, Letterhead, Envelope, Fax Template' },
      { heading: false, message: 'MS Word Letterhead' },
      { heading: true, message: 'Website Design' },
      { heading: false, message: '5 Page Website' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: 'Team of Expert Designers & Developers' },
      { heading: false, message: '8 Stock images' },
      { heading: false, message: '5 Banner Designs' },
      { heading: false, message: 'jQuery Sliders' },
      { heading: false, message: 'Free Google Friendly Sitemap' },
      { heading: false, message: 'Facebook Page Design' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Logo Design Final Files (.PNG, .JPG, .PDF)' },
      { heading: false, message: 'Website Design Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: 'Complete Deployment' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '46',
    name: 'Start Up Combo Package',
    price: '1988.00',
    discountedPrice: ' $994.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Combo',
    points: [
      { heading: true, message: 'Logo Design' },
      { heading: false, message: 'Unlimited Logo Design Concepts' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Icon Design' },
      { heading: false, message: 'All Final File Formats' },
      { heading: true, message: 'Stationary Design ' },
      { heading: false, message: 'Business Card, Letterhead, Envelope' },
      { heading: false, message: 'MS Word Letterhead' },
      { heading: false, message: 'Website Design' },
      { heading: false, message: 'UNLIMITED Pages Website' },
      { heading: false, message: 'Content Management System (CMS)' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: '5 Stock Photos + 3 Banner Designs' },
      { heading: false, message: 'Any 3 Social Media Platforms' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: false, message: 'Complete Deployment' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Dedicated Account Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: 'Complete Deployment' },
    ],
  },
  {
    id: '47',
    name: 'Professional Combo Package',
    price: '2599.00',
    discountedPrice: ' $1299.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Combo',
    points: [
      { heading: true, message: 'Logo Design' },
      { heading: false, message: 'Unlimited Logo Concepts' },
      { heading: false, message: '8 Dedicated Designers' },
      { heading: false, message: 'Icon Design' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'All file formats' },
      { heading: false, message: '– Print Materials' },
      { heading: false, message: '2 Free Custom Stationary Designs' },
      { heading: false, message: 'MS Word Letterhead' },
      { heading: false, message: 'Free Trifold Brochure Design' },
      { heading: true, message: 'Website Design' },
      { heading: false, message: 'Unlimited Pages Design' },
      { heading: false, message: 'Conceptual and Dynamic Liquid Website' },
      { heading: false, message: 'Team of Expert Designers & Developers' },
      { heading: false, message: 'Word Press OR Custom Php' },
      { heading: false, message: 'Content Management System' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: 'Online Reservation/Appointment Tool (Optional)' },
      { heading: false, message: 'Custom Forms' },
      { heading: false, message: 'Lead Capturing Forms (Optional)' },
      { heading: false, message: 'Newsfeed Integration' },
      { heading: false, message: 'Social Media Integration' },
      { heading: false, message: 'Search Engine Submission' },
      { heading: false, message: '15 Stock images' },
      { heading: false, message: '8 Unique Banner Designs' },
      { heading: false, message: 'jQuery Sliders' },
      { heading: false, message: 'Free Google Friendly Sitemap' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: true, message: 'Social Media Page Design' },
      { heading: false, message: 'Facebook Page Design' },
      { heading: false, message: 'Twitter Page Design' },
      { heading: false, message: 'YouTube Page Design' },
      { heading: false, message: 'Google+ Page Design' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Dedicated Account Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '48',
    name: 'Elite Combo Package',
    price: '3059.00',
    discountedPrice: ' $1529.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Combo',
    points: [
      { heading: true, message: 'Logo Design' },
      { heading: false, message: '9 Logo Design Idea(s)' },
      { heading: false, message: 'By 4 Expert Level Designer(s)' },
      { heading: false, message: 'Free Icon Design' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: '2 to 3 Business Days TAT' },
      { heading: true, message: 'Stationary Design' },
      { heading: false, message: 'Letterhead Design' },
      { heading: false, message: 'Business Card Design' },
      { heading: false, message: 'Envelope Design' },
      { heading: false, message: 'Email Signature Design' },
      { heading: false, message: 'Electronic Letterhead' },
      { heading: false, message: 'Invoice Design' },
      { heading: true, message: 'Website Design' },
      { heading: false, message: 'Unique 5 Pages Website Design' },
      { heading: false, message: 'Custom, Interactive, Dynamic & High End Web Design' },
      { heading: false, message: 'Custom WordPress Development' },
      { heading: false, message: '5 Stock Images' },
      { heading: false, message: '5 Banner Designs' },
      { heading: false, message: 'Sliding Banners' },
      { heading: false, message: 'Unlimited Revisions' },
      { heading: false, message: 'Special Hoover Effects' },
      { heading: false, message: 'Content Management System (WordPress)' },
      { heading: false, message: 'Mobile Responsive' },
      { heading: false, message: 'Online Appointment/Booking/Scheduling/Online Ordering Integration (If Required)' },
      { heading: false, message: 'FREE 12 Months Domain Name' },
      { heading: false, message: 'FREE 12 Month Hosting' },
      { heading: false, message: '5 Professional Email ID’s' },
      { heading: false, message: 'Social Media Page Integration' },
      { heading: false, message: 'Google Friendly Sitemap' },
      { heading: false, message: 'Search Engine Submission' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: false, message: 'Industry specified Team of Expert Designers and Developers' },
      { heading: false, message: 'Complete Deployment' },
      { heading: false, message: 'Social Media Page Design ' },
      { heading: false, message: 'Facebook Icon Image & Banner Design' },
      { heading: false, message: 'Twitter Icon Image & Banner Design' },
      { heading: false, message: 'Google+ Icon Image & Banner Design' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Logo Design Final Files (.AI, .PSD, .EPS, .PNG, .JPG, .PDF, .TIFF)' },
      { heading: false, message: 'Website Design Complete Source Files' },
      { heading: false, message: 'Dedicated Project Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
      { heading: true, message: 'Add on' },
      { heading: false, message: 'Professional Content/Copywriting' },
      { heading: false, message: 'Online Payment Integration' },
      { heading: false, message: 'Shopping Cart Integration' },
      { heading: false, message: 'Additional Professional Email ID' },
    ],
  },
  {
    id: '49',
    name: 'Business Combo Package',
    price: '3599.00',
    discountedPrice: ' $1799.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Combo',
    points: [
      { heading: true, message: 'Logo Design' },
      { heading: false, message: 'Unlimited Logo Design Idea(s)' },
      { heading: false, message: '8 Dedicated Designers' },
      { heading: false, message: 'Icon Design' },
      { heading: false, message: 'All final file formats' },
      { heading: true, message: 'Stationary Design' },
      { heading: false, message: '2 Free Custom Stationary Designs' },
      { heading: false, message: 'MS Word Letterhead' },
      { heading: false, message: 'Invoice Design' },
      { heading: false, message: 'FREE Tri fold Brochure Design' },
      { heading: true, message: 'Website Design' },
      { heading: false, message: 'Unlimited Pages Website' },
      { heading: false, message: 'Conceptual and Dynamic Website' },
      { heading: false, message: 'Word Press OR CUSTOM PHP' },
      { heading: false, message: 'Content Management System (CMS)' },
      { heading: false, message: 'Easy Product Search' },
      { heading: false, message: 'Product Reviews' },
      { heading: false, message: 'Unlimited Products' },
      { heading: false, message: 'Unlimited Categories' },
      { heading: false, message: 'Promotional Product Showcase' },
      { heading: false, message: 'New Product Showcase' },
      { heading: false, message: 'Full Shopping Cart Integration' },
      { heading: false, message: 'Payment Module Integration' },
      { heading: false, message: 'Sales & Inventory Management' },
      { heading: false, message: 'Custom Forms' },
      { heading: false, message: 'Lead Capturing Forms (Optional)' },
      { heading: false, message: 'Newsfeed Integration' },
      { heading: false, message: 'Social Media Integration' },
      { heading: false, message: 'Search Engine Submission' },
      { heading: false, message: 'Team of Dedicated Designers, Developers and Brand Experts' },
      { heading: false, message: '20 Stock images' },
      { heading: false, message: '6 Unique Banner Designs' },
      { heading: false, message: 'jQuery Slider' },
      { heading: false, message: 'Free Google Friendly Sitemap' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: true, message: 'Social Media Page Design' },
      { heading: false, message: 'Facebook Page Design' },
      { heading: false, message: 'Twitter Page Design' },
      { heading: false, message: 'YouTube Page Design' },
      { heading: false, message: 'Google+ Page Design' },
      { heading: false, message: 'Pinterest Page Design' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Dedicated Account Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
  {
    id: '50',
    name: 'Gold Combo Package',
    price: '7999.00',
    discountedPrice: ' $3999.00',
    desc: 'Suitable for potential super-startups and brand revamps for companies.',
    category: 'Combo',
    points: [
      { heading: true, message: 'Logo Design' },
      { heading: false, message: 'Unlimited Logo Design Idea(s)' },
      { heading: false, message: '8 Dedicated Designers' },
      { heading: false, message: 'Icon Design' },
      { heading: false, message: 'All final file formats' },
      { heading: true, message: 'Stationary Design' },
      { heading: false, message: '2 Free Custom Stationary Designs' },
      { heading: false, message: 'MS Word Letterhead' },
      { heading: false, message: 'Invoice Design' },
      { heading: false, message: 'FREE Tri fold Brochure Design' },
      { heading: true, message: 'Website Design' },
      { heading: false, message: 'Unlimited Pages Website' },
      { heading: false, message: 'Conceptual and Dynamic Website' },
      { heading: false, message: 'Word Press OR CUSTOM PHP' },
      { heading: false, message: 'Content Management System (CMS)' },
      { heading: false, message: 'Easy Product Search' },
      { heading: false, message: 'Product Reviews' },
      { heading: false, message: 'Unlimited Products' },
      { heading: false, message: 'Unlimited Categories' },
      { heading: false, message: 'Promotional Product Showcase' },
      { heading: false, message: 'New Product Showcase' },
      { heading: false, message: 'Full Shopping Cart Integration' },
      { heading: false, message: 'Payment Module Integration' },
      { heading: false, message: 'Sales & Inventory Management' },
      { heading: false, message: 'Custom Forms' },
      { heading: false, message: 'Lead Capturing Forms (Optional)' },
      { heading: false, message: 'Newsfeed Integration' },
      { heading: false, message: 'Social Media Integration' },
      { heading: false, message: 'Search Engine Submission' },
      { heading: false, message: 'Team of Dedicated Designers, Developers and Brand Experts' },
      { heading: false, message: '20 Stock images' },
      { heading: false, message: '6 Unique Banner Designs' },
      { heading: false, message: 'jQuery Slider' },
      { heading: false, message: 'Free Google Friendly Sitemap' },
      { heading: false, message: 'Complete W3C Certified HTML' },
      { heading: true, message: 'Social Media Page Design' },
      { heading: false, message: 'Facebook Page Design' },
      { heading: false, message: 'Twitter Page Design' },
      { heading: false, message: 'YouTube Page Design' },
      { heading: false, message: 'Google+ Page Design' },
      { heading: false, message: 'Pinterest Page Design' },
      { heading: true, message: 'Value Added Services' },
      { heading: false, message: 'Dedicated Account Manager' },
      { heading: false, message: '100% Ownership Rights' },
      { heading: false, message: '100% Satisfaction Guarantee' },
      { heading: false, message: '100% Money Back Guarantee' },
      { heading: false, message: '*NO MONTHLY OR ANY HIDDEN FEE*' },
    ],
  },
];
