import { subCategoriesType } from "@/types";

export const subCategories:subCategoriesType[] = [
    {
        id: "1",
        name: "Iconic Logo",
        image: "/images/Sub_Categories/logo_design/Iconic_Logo.webp",
        link:"#",
        cat: "Logo Design",
    },
    {
        id: "2",
        name: "Typographic Logo",
        image: "/images/Sub_Categories/logo_design/Typographic_Logo.webp",
        link:"#",
        cat: "Logo Design",
    },
    {
        id: "3",
        name: "Illustrative Logo",
        image: "/images/Sub_Categories/logo_design/Illustrative_Logo.webp",
        link:"#",
        cat: "Logo Design",
    },
    {
        id: "4",
        name: "Animated Logo",
        image: "/images/Sub_Categories/logo_design/Animated_Logo.webp",
        link:"#",
        cat: "Logo Design",
    },
    {
        id: "5",
        name: "3D Logo",
        image: "/images/Sub_Categories/logo_design/3D_Logo.webp",
        link:"#",
        cat: "Logo Design",
    },
    {
        id: "6",
        name: "Wordmark Logo",
        image: "/images/Sub_Categories/logo_design/Wordmark_Logo.webp",
        link:"#",
        cat: "Logo Design",
    },
    {
        id: "7",
        name: "Emblem Logo",
        image: "/images/Sub_Categories/logo_design/Emblem_Logo.webp",
        link:"#",
        cat: "Logo Design",
    },
    {
        id: "8",
        name: "2D Logo",
        image: "/images/Sub_Categories/logo_design/2D_Logo.webp",
        link:"#",
        cat: "Logo Design",
    },
    {
        id: "9",
        name: "Static Website",
        image: "/images/Sub_Categories/Website_Design/Static_website.webp",
        link:"#",
        cat: "Website Design",
    },
    {
        id: "10",
        name: "B2B Portal",
        image: "/images/Sub_Categories/Website_Design/B2B_Portal.webp",
        link:"#",
        cat: "Website Design",
    },
    {
        id: "11",
        name: "B2C Portal",
        image: "/images/Sub_Categories/Website_Design/B2C_Portal.webp",
        link:"#",
        cat: "Website Design",
    },
    {
        id: "12",
        name: "Ecommerce Website",
        image: "/images/Sub_Categories/Website_Design/Ecommerce_Website.webp",
        link:"#",
        cat: "Website Design",
    },
    {
        id: "13",
        name: "Web Portal",
        image: "/images/Sub_Categories/Website_Design/Web_Portal.webp",
        link:"#",
        cat: "Website Design",
    },
    {
        id: "14",
        name: "Web Development",
        image: "/images/Sub_Categories/Website_Design/Web_Development.webp",
        link:"#",
        cat: "Website Design",
    },
    {
        id: "15",
        name: "SEO",
        image: "/images/Sub_Categories/Digital_Marketing/SEO.webp",
        link:"#",
        cat: "Digital Marketing",
    },
    {
        id: "16",
        name: "SMM",
        image: "/images/Sub_Categories/Digital_Marketing/SMM.webp",
        link:"#",
        cat: "Digital Marketing",
    },
    {
        id: "17",
        name: "PPC",
        image: "/images/Sub_Categories/Digital_Marketing/PPC.webp",
        link:"#",
        cat: "Digital Marketing",
    },
    {
        id: "18",
        name: "Email Marketing",
        image: "/images/Sub_Categories/Digital_Marketing/Email_Marketing.webp",
        link:"#",
        cat: "Digital Marketing",
    },
    {
        id: "19",
        name: "Display Advertising",
        image: "/images/Sub_Categories/Digital_Marketing/Display_Advertisinng.webp",
        link:"#",
        cat: "Digital Marketing",
    },
    {
        id: "20",
        name: "ORM",
        image: "/images/Sub_Categories/Digital_Marketing/ORM.webp",
        link:"#",
        cat: "Digital Marketing",
    },
    {
        id: "21",
        name: "Hybrid App",
        image: "/images/Sub_Categories/Mobile_Apps/Hybrid_App.webp",
        link:"#",
        cat: "Mobile Apps",
    },
    {
        id: "22",
        name: "Native App",
        image: "/images/Sub_Categories/Mobile_Apps/Native_App.webp",
        link:"#",
        cat: "Mobile Apps",
    },
    {
        id: "23",
        name: "Android App",
        image: "/images/Sub_Categories/Mobile_Apps/Android_App.webp",
        link:"#",
        cat: "Mobile Apps",
    },
    {
        id: "24",
        name: "iOS App",
        image: "/images/Sub_Categories/Mobile_Apps/iOS_App.webp",
        link:"#",
        cat: "Mobile Apps",
    },
    {
        id: "25",
        name: "React Native App",
        image: "/images/Sub_Categories/Mobile_Apps/React_Native_App.webp",
        link:"#",
        cat: "Mobile Apps",
    },
    {
        id: "26",
        name: "Flutter App",
        image: "/images/Sub_Categories/Mobile_Apps/Flutter_App.webp",
        link:"#",
        cat: "Mobile Apps",
    },
    {
        id: "27",
        name: "2D Animation",
        image: "/images/Sub_Categories/Video_Animation/2D_Animation.webp",
        link:"#",
        cat: "Animation",
    },
    {
        id: "28",
        name: "3D Animation",
        image: "/images/Sub_Categories/Video_Animation/3D_Animation.webp",
        link:"#",
        cat: "Animation",
    },
    {
        id: "29",
        name: "Illustration",
        image: "/images/Sub_Categories/Video_Animation/Illustration.webp",
        link:"#",
        cat: "Animation",
    },
    {
        id: "30",
        name: "Logo Animation",
        image: "/images/Sub_Categories/Video_Animation/Logo_Animation.webp",
        link:"#",
        cat: "Animation",
    },
    {
        id: "31",
        name: "Whiteboard Animation",
        image: "/images/Sub_Categories/Video_Animation/Whiteboard_Animation.webp",
        link:"#",
        cat: "Animation",
    },
    {
        id: "32",
        name: "Explainer Videos",
        image: "/images/Sub_Categories/Video_Animation/Explainer_Videos.webp",
        link:"#",
        cat: "Animation",
    },
    {
        id: "33",
        name: "Banner Design",
        image: "/images/Sub_Categories/Marketing_Collateral/Banner_Design.webp",
        link:"#",
        cat: "Marketing Collateral",
    },
    {
        id: "34",
        name: "Letter Head",
        image: "/images/Sub_Categories/Marketing_Collateral/Letter_Head.webp",
        link:"#",
        cat: "Marketing Collateral",
    },
    {
        id: "35",
        name: "Buisness Card",
        image: "/images/Sub_Categories/Marketing_Collateral/Business_Card.webp",
        link:"#",
        cat: "Marketing Collateral",
    },
    {
        id: "36",
        name: "Magazine",
        image: "/images/Sub_Categories/Marketing_Collateral/Magazine.webp",
        link:"#",
        cat: "Marketing Collateral",
    },
    {
        id: "37",
        name: "Brochure",
        image: "/images/Sub_Categories/Marketing_Collateral/Brochure.webp",
        link:"#",
        cat: "Marketing Collateral",
    },
    {
        id: "38",
        name: "Stationary",
        image: "/images/Sub_Categories/Marketing_Collateral/Stationery.webp",
        link:"#",
        cat: "Marketing Collateral",
    },
]